export type QuestionType = 'mcq' | 'numerical' | 'true_false' | 'fill_blank'
export type Difficulty = 'easy' | 'medium' | 'hard'

export interface Question {
  id: string
  chapter: string
  topic: string
  type: QuestionType
  difficulty: Difficulty
  question: string
  options?: string[]
  answer: string | boolean
  explanation: string
  source: string
}

export const questionBank: Question[] = [
  // ===== CHAPTER 1: BASIC CONCEPTS =====
  { id:'q_ch1_001', chapter:'ch1', topic:'Charge and Current', type:'mcq', difficulty:'easy', question:'The unit of electric current is:', options:['Coulomb','Ampere','Volt','Watt'], answer:'Ampere', explanation:'Current i = dq/dt. Its SI unit is Ampere (A), where 1 A = 1 C/s.', source:'Sadiku Ch1' },
  { id:'q_ch1_002', chapter:'ch1', topic:'Charge and Current', type:'mcq', difficulty:'easy', question:'How much charge is represented by 4,600 electrons?', options:['7.36 × 10⁻¹⁶ C','4.6 × 10⁻¹⁹ C','7.36 × 10⁻¹⁹ C','1.6 × 10⁻¹⁹ C'], answer:'7.36 × 10⁻¹⁶ C', explanation:'Q = 4600 × 1.6 × 10⁻¹⁹ = 7.36 × 10⁻¹⁶ C.', source:'Sadiku Ch1' },
  { id:'q_ch1_003', chapter:'ch1', topic:'Power and Energy', type:'numerical', difficulty:'easy', question:'A current of 3 A flows through a 5 Ω resistor. Calculate the power dissipated.', answer:'45 W', explanation:'P = I²R = 3² × 5 = 45 W', source:'Sadiku Ch1' },
  { id:'q_ch1_004', chapter:'ch1', topic:'Power and Energy', type:'numerical', difficulty:'medium', question:'A 600-W TV is on for 4 hours. At 10 cents/kWh, how much does it cost?', answer:'24 cents', explanation:'Energy = 0.6 kW × 4 h = 2.4 kWh. Cost = 2.4 × 10 = 24 cents.', source:'Sadiku Ch1 P1.39' },
  { id:'q_ch1_005', chapter:'ch1', topic:'Charge and Current', type:'numerical', difficulty:'medium', question:'A lightning bolt carried 2 kA for 3 ms. How many coulombs?', answer:'6 C', explanation:'Q = I × t = 2000 × 0.003 = 6 C', source:'Sadiku Ch1 P1.33' },
  { id:'q_ch1_006', chapter:'ch1', topic:'Power and Energy', type:'mcq', difficulty:'easy', question:'Which is NOT a passive element?', options:['Resistor','Capacitor','Voltage Source','Inductor'], answer:'Voltage Source', explanation:'Voltage and current sources are active — they supply energy.', source:'Sadiku Ch1' },
  { id:'q_ch1_007', chapter:'ch1', topic:'Systems of Units', type:'mcq', difficulty:'easy', question:'The SI unit of charge is:', options:['Ampere','Volt','Coulomb','Joule'], answer:'Coulomb', explanation:'Electric charge unit is Coulomb (C). 1 A = 1 C/s.', source:'Sadiku Ch1' },
  { id:'q_ch1_008', chapter:'ch1', topic:'Voltage', type:'true_false', difficulty:'easy', question:'Voltage is defined as the energy required to move a unit charge from one point to another.', answer:'true', explanation:'Voltage v = dw/dq — energy per unit charge.', source:'Sadiku Ch1' },
  { id:'q_ch1_009', chapter:'ch1', topic:'Power and Energy', type:'fill_blank', difficulty:'easy', question:'The relationship between power, voltage, and current is: P = ____', answer:'v × i', explanation:'P = v·i (DC). Unit is Watts (W).', source:'Sadiku Ch1' },
  { id:'q_ch1_010', chapter:'ch1', topic:'Charge and Current', type:'mcq', difficulty:'medium', question:'If q(t) = 5t² + 3t mC, what is the current at t = 2 s?', options:['23 mA','23 A','10 mA','13 mA'], answer:'23 mA', explanation:'i = dq/dt = 10t + 3. At t=2: i = 20 + 3 = 23 mA.', source:'Sadiku Ch1' },
  { id:'q_ch1_011', chapter:'ch1', topic:'Power and Energy', type:'numerical', difficulty:'hard', question:'A battery has an open-circuit voltage of 12 V and internal resistance of 0.5 Ω. What is the maximum power delivered to an external load?', answer:'72 W', explanation:'For max power, R_L = R_int = 0.5 Ω. P_max = V²/(4R) = 144/2 = 72 W.', source:'Sadiku Ch1' },
  { id:'q_ch1_012', chapter:'ch1', topic:'Systems of Units', type:'mcq', difficulty:'easy', question:'1 kilowatt-hour (kWh) equals how many joules?', options:['3.6 × 10³ J','3.6 × 10⁶ J','3.6 × 10⁹ J','1000 J'], answer:'3.6 × 10⁶ J', explanation:'1 kWh = 1000 W × 3600 s = 3.6 × 10⁶ J.', source:'Sadiku Ch1' },

  // ===== CHAPTER 2: BASIC LAWS =====
  { id:'q_ch2_001', chapter:'ch2', topic:"Ohm's Law", type:'mcq', difficulty:'easy', question:'A resistor has 12 V across it and 3 A through it. What is its resistance?', options:['0.25 Ω','4 Ω','36 Ω','15 Ω'], answer:'4 Ω', explanation:"Ohm's Law: R = V/I = 12/3 = 4 Ω", source:'Sadiku Ch2' },
  { id:'q_ch2_002', chapter:'ch2', topic:'KCL', type:'mcq', difficulty:'easy', question:"Kirchhoff's Current Law (KCL) states that:", options:['Sum of all voltages in a loop equals zero','Sum of currents entering a node equals the sum leaving','Voltage is proportional to current','Power in = Power out'], answer:'Sum of currents entering a node equals the sum leaving', explanation:'KCL: Σi_in = Σi_out — conservation of charge.', source:'Sadiku Ch2' },
  { id:'q_ch2_003', chapter:'ch2', topic:'KVL', type:'mcq', difficulty:'easy', question:"Kirchhoff's Voltage Law (KVL) states that:", options:['Sum of currents at a node is zero','Sum of all voltages around any closed loop is zero','Resistance is constant','Power consumed equals power supplied'], answer:'Sum of all voltages around any closed loop is zero', explanation:'KVL: Σv = 0 around any closed loop — conservation of energy.', source:'Sadiku Ch2' },
  { id:'q_ch2_004', chapter:'ch2', topic:'Series Resistance', type:'numerical', difficulty:'easy', question:'Three resistors 4 Ω, 6 Ω, and 10 Ω are in series. Find R_eq.', answer:'20 Ω', explanation:'R_eq = 4 + 6 + 10 = 20 Ω', source:'Boylestad Ch5' },
  { id:'q_ch2_005', chapter:'ch2', topic:'Parallel Resistance', type:'numerical', difficulty:'medium', question:'Two resistors 6 Ω and 12 Ω are in parallel. Find R_eq.', answer:'4 Ω', explanation:'R_eq = (6×12)/(6+12) = 72/18 = 4 Ω', source:'Boylestad Ch6' },
  { id:'q_ch2_006', chapter:'ch2', topic:'Voltage Divider', type:'numerical', difficulty:'medium', question:'In a series circuit: V_s = 24 V, R1 = 8 Ω, R2 = 16 Ω. Find V across R2.', answer:'16 V', explanation:'V_R2 = (R2/(R1+R2))×V_s = (16/24)×24 = 16 V', source:'Sadiku Ch2' },
  { id:'q_ch2_007', chapter:'ch2', topic:'Current Divider', type:'numerical', difficulty:'medium', question:'Total current 12 A splits between R1=4 Ω and R2=8 Ω in parallel. Find current through R1.', answer:'8 A', explanation:'I1 = (R2/(R1+R2))×I = (8/12)×12 = 8 A', source:'Sadiku Ch2' },
  { id:'q_ch2_008', chapter:'ch2', topic:"Ohm's Law", type:'true_false', difficulty:'easy', question:"Ohm's Law states that voltage is directly proportional to current for a linear resistor.", answer:'true', explanation:'V = IR: voltage = current × resistance (constant R implies linear relationship).', source:'Sadiku Ch2' },
  { id:'q_ch2_009', chapter:'ch2', topic:'KVL', type:'numerical', difficulty:'medium', question:'A series circuit has V_s=20V, R1=5Ω, R2=3Ω, R3=2Ω. Find current I.', answer:'2 A', explanation:'I = V_s/(R1+R2+R3) = 20/10 = 2 A', source:'Boylestad Ch5' },
  { id:'q_ch2_010', chapter:'ch2', topic:'Parallel Resistance', type:'mcq', difficulty:'medium', question:'What is the equivalent resistance of 3 identical 12 Ω resistors in parallel?', options:['36 Ω','12 Ω','4 Ω','6 Ω'], answer:'4 Ω', explanation:'For n equal resistors in parallel: R_eq = R/n = 12/3 = 4 Ω', source:'Boylestad Ch6' },
  { id:'q_ch2_011', chapter:'ch2', topic:'Wye-Delta', type:'mcq', difficulty:'hard', question:'In a balanced Δ network with R=30 Ω each, the equivalent Y resistances are:', options:['90 Ω','10 Ω','30 Ω','15 Ω'], answer:'10 Ω', explanation:'Y resistor = R_Δ/3 = 30/3 = 10 Ω for balanced networks.', source:'Sadiku Ch2' },
  { id:'q_ch2_012', chapter:'ch2', topic:'KCL', type:'numerical', difficulty:'hard', question:'At a node, currents entering: 5A and 3A. Currents leaving: 2A and I_x. Find I_x.', answer:'6 A', explanation:'KCL: 5+3 = 2+I_x → I_x = 6 A', source:'Sadiku Ch2' },

  // ===== CHAPTER 3: METHODS OF ANALYSIS =====
  { id:'q_ch3_001', chapter:'ch3', topic:'Nodal Analysis', type:'mcq', difficulty:'easy', question:'In nodal analysis, the reference node is called the:', options:['Supernode','Ground node','Voltage node','Datum node'], answer:'Datum node', explanation:'The reference (ground) node is called the datum node. It is assigned 0 V.', source:'Sadiku Ch3' },
  { id:'q_ch3_002', chapter:'ch3', topic:'Mesh Analysis', type:'mcq', difficulty:'easy', question:'Mesh analysis is based on:', options:['KCL','KVL','Ohm\'s Law only','Superposition'], answer:'KVL', explanation:'Mesh analysis applies KVL around each mesh to find mesh currents.', source:'Sadiku Ch3' },
  { id:'q_ch3_003', chapter:'ch3', topic:'Nodal Analysis', type:'mcq', difficulty:'medium', question:'A supernode is formed when a:', options:['Current source is between two non-reference nodes','Voltage source is between two non-reference nodes','Resistor is between two nodes','Current source is in parallel with a resistor'], answer:'Voltage source is between two non-reference nodes', explanation:'A supernode is formed by a voltage source between two non-reference nodes.', source:'Sadiku Ch3' },
  { id:'q_ch3_004', chapter:'ch3', topic:'Mesh Analysis', type:'true_false', difficulty:'medium', question:'A supermesh is created when a current source is shared by two meshes.', answer:'true', explanation:'A supermesh excludes the branch with the current source, then applies KVL around the combined outer loop.', source:'Sadiku Ch3' },
  { id:'q_ch3_005', chapter:'ch3', topic:'Nodal Analysis', type:'numerical', difficulty:'hard', question:'A circuit has two nodes (besides ground): Node 1 connected via 2Ω to 10V source (ground side), and 4Ω between Node 1 and Node 2, and 2Ω from Node 2 to ground. With 5A current source from ground to Node 1. Find V1 and V2.', answer:'V1≈13.3V, V2≈6.67V (approx)', explanation:'Apply KCL at each node using conductances. System of equations: (1/2+1/4)V1 - (1/4)V2 = 5+10/2; -(1/4)V1 + (1/4+1/2)V2 = 0', source:'Sadiku Ch3' },
  { id:'q_ch3_006', chapter:'ch3', topic:'Mesh Analysis', type:'mcq', difficulty:'medium', question:'For a circuit with 3 meshes and 1 current source shared between meshes 1 and 2, how many independent mesh equations are needed?', options:['3','2','1','4'], answer:'2', explanation:'With a supermesh combining meshes 1 and 2, plus one constraint equation, you get 2 independent KVL equations + 1 supermesh constraint = 3 equations total for 3 unknowns.', source:'Sadiku Ch3' },

  // ===== CHAPTER 4: CIRCUIT THEOREMS =====
  { id:'q_ch4_001', chapter:'ch4', topic:"Thévenin's Theorem", type:'mcq', difficulty:'easy', question:"Thévenin's theorem replaces a complex network with:", options:['A current source in parallel with resistance','A voltage source in series with resistance','A single resistor','Two voltage sources'], answer:'A voltage source in series with resistance', explanation:"Thévenin equivalent = V_Th (voltage source) in series with R_Th.", source:'Sadiku Ch4' },
  { id:'q_ch4_002', chapter:'ch4', topic:"Norton's Theorem", type:'mcq', difficulty:'easy', question:"Norton's equivalent circuit consists of:", options:['V_N in series with R_N','I_N in parallel with R_N','V_N in parallel with R_N','I_N in series with R_N'], answer:'I_N in parallel with R_N', explanation:"Norton equivalent = I_N (current source) in parallel with R_N.", source:'Sadiku Ch4' },
  { id:'q_ch4_003', chapter:'ch4', topic:'Maximum Power Transfer', type:'mcq', difficulty:'easy', question:'Maximum power is transferred to the load when R_L equals:', options:['Zero','Infinity','R_Th','2R_Th'], answer:'R_Th', explanation:'P_max when R_L = R_Th. P_max = V_Th²/(4R_Th).', source:'Sadiku Ch4' },
  { id:'q_ch4_004', chapter:'ch4', topic:'Superposition', type:'mcq', difficulty:'easy', question:'When applying superposition, voltage sources are replaced by:', options:['Open circuits','Short circuits','Current sources','Resistors'], answer:'Short circuits', explanation:'To deactivate a voltage source: replace with short circuit. Current source: replace with open circuit.', source:'Sadiku Ch4' },
  { id:'q_ch4_005', chapter:'ch4', topic:"Thévenin's Theorem", type:'numerical', difficulty:'medium', question:'A circuit has V_Th = 20 V and R_Th = 5 Ω. What is the maximum power deliverable to a load?', answer:'20 W', explanation:'P_max = V_Th²/(4R_Th) = 400/20 = 20 W', source:'Sadiku Ch4' },
  { id:'q_ch4_006', chapter:'ch4', topic:'Source Transformation', type:'true_false', difficulty:'medium', question:'A 10V voltage source in series with 5Ω can be transformed to a 2A current source in parallel with 5Ω.', answer:'true', explanation:'I = V/R = 10/5 = 2 A. The resistance stays the same (5Ω) in the Norton equivalent.', source:'Sadiku Ch4' },

  // ===== CHAPTER 5: OPERATIONAL AMPLIFIERS =====
  { id:'q_ch5_001', chapter:'ch5', topic:'Inverting Amplifier', type:'mcq', difficulty:'easy', question:'The gain of an inverting amplifier with Rf=10kΩ and R1=2kΩ is:', options:['5','-5','0.2','-0.2'], answer:'-5', explanation:'A_v = -Rf/R1 = -10k/2k = -5. Negative sign indicates phase inversion.', source:'Sadiku Ch5' },
  { id:'q_ch5_002', chapter:'ch5', topic:'Noninverting Amplifier', type:'mcq', difficulty:'easy', question:'The minimum gain of a noninverting amplifier is:', options:['0','-1','1','Undefined'], answer:'1', explanation:'A_v = 1 + Rf/R1 ≥ 1. Minimum gain is 1 (voltage follower when Rf=0, R1=∞).', source:'Sadiku Ch5' },
  { id:'q_ch5_003', chapter:'ch5', topic:'Ideal Op Amp', type:'true_false', difficulty:'easy', question:'In an ideal op amp, the input currents at both terminals are zero.', answer:'true', explanation:'Ideal op amp: infinite input impedance → i+ = i- = 0. Infinite gain → v+ = v- (virtual short).', source:'Sadiku Ch5' },
  { id:'q_ch5_004', chapter:'ch5', topic:'Summing Amplifier', type:'numerical', difficulty:'medium', question:'A summing amplifier has Rf=10kΩ, R1=5kΩ, R2=10kΩ. If V1=1V and V2=2V, find V_o.', answer:'-4 V', explanation:'V_o = -Rf(V1/R1 + V2/R2) = -10k(1/5k + 2/10k) = -10k(0.2+0.2) = -4 V', source:'Sadiku Ch5' },
  { id:'q_ch5_005', chapter:'ch5', topic:'Difference Amplifier', type:'numerical', difficulty:'medium', question:'A difference amplifier has R1=R3=1kΩ, R2=R4=10kΩ. If V1=2V, V2=3V, find V_o.', answer:'10 V', explanation:'V_o = (R2/R1)(V2-V1) = (10k/1k)(3-2) = 10 V', source:'Sadiku Ch5' },

  // ===== CHAPTER 6: CAPACITORS & INDUCTORS =====
  { id:'q_ch6_001', chapter:'ch6', topic:'Capacitors', type:'mcq', difficulty:'easy', question:'The current through a capacitor is related to voltage by:', options:['i = v/C','i = C·dv/dt','v = C·di/dt','i = C·v'], answer:'i = C·dv/dt', explanation:'Capacitor: i = C·dv/dt. Current flows only when voltage is changing.', source:'Sadiku Ch6' },
  { id:'q_ch6_002', chapter:'ch6', topic:'Inductors', type:'mcq', difficulty:'easy', question:'The voltage across an inductor is:', options:['v = i/L','v = L·di/dt','i = L·dv/dt','v = L·i'], answer:'v = L·di/dt', explanation:'Inductor: v = L·di/dt. Voltage appears only when current is changing.', source:'Sadiku Ch6' },
  { id:'q_ch6_003', chapter:'ch6', topic:'Capacitors', type:'true_false', difficulty:'easy', question:'A capacitor acts as an open circuit in DC steady state.', answer:'true', explanation:'In DC steady state, dv/dt=0, so i = C·dv/dt = 0. No current flows → open circuit.', source:'Sadiku Ch6' },
  { id:'q_ch6_004', chapter:'ch6', topic:'Inductors', type:'true_false', difficulty:'easy', question:'An inductor acts as a short circuit in DC steady state.', answer:'true', explanation:'In DC steady state, di/dt=0, so v = L·di/dt = 0. No voltage → short circuit.', source:'Sadiku Ch6' },
  { id:'q_ch6_005', chapter:'ch6', topic:'Capacitors', type:'numerical', difficulty:'medium', question:'Energy stored in a 5 μF capacitor charged to 100 V:', answer:'25 mJ', explanation:'w = ½Cv² = ½×5×10⁻⁶×100² = 25×10⁻³ J = 25 mJ', source:'Sadiku Ch6' },
  { id:'q_ch6_006', chapter:'ch6', topic:'Inductors', type:'numerical', difficulty:'medium', question:'Energy stored in a 10 mH inductor carrying 4 A:', answer:'80 mJ', explanation:'w = ½Li² = ½×0.01×16 = 0.08 J = 80 mJ', source:'Sadiku Ch6' },
  { id:'q_ch6_007', chapter:'ch6', topic:'Capacitors', type:'mcq', difficulty:'medium', question:'Three capacitors of 4μF, 6μF, 12μF are in series. R_eq is:', options:['22 μF','2 μF','12 μF','4 μF'], answer:'2 μF', explanation:'1/C_eq = 1/4+1/6+1/12 = 3/12+2/12+1/12 = 6/12 → C_eq = 2 μF', source:'Sadiku Ch6' },

  // ===== CHAPTER 7: FIRST-ORDER CIRCUITS =====
  { id:'q_ch7_001', chapter:'ch7', topic:'RC Circuit', type:'mcq', difficulty:'easy', question:'The time constant of an RC circuit is:', options:['R/C','RC','C/R','√(RC)'], answer:'RC', explanation:'τ = RC. After one time constant, the voltage decays to 36.8% of initial value.', source:'Sadiku Ch7' },
  { id:'q_ch7_002', chapter:'ch7', topic:'RL Circuit', type:'mcq', difficulty:'easy', question:'The time constant of an RL circuit is:', options:['RL','R/L','L/R','√(L/R)'], answer:'L/R', explanation:'τ = L/R for RL circuits.', source:'Sadiku Ch7' },
  { id:'q_ch7_003', chapter:'ch7', topic:'RC Circuit', type:'numerical', difficulty:'medium', question:'An RC circuit has R=10kΩ, C=50μF. The initial voltage is 20V. Find v(t) after 0.5s.', answer:'≈ 7.36 V', explanation:'τ = RC = 10k×50μ = 0.5 s. v(t) = 20e^(-t/0.5). At t=0.5: v = 20e^(-1) ≈ 20×0.368 = 7.36 V', source:'Sadiku Ch7' },
  { id:'q_ch7_004', chapter:'ch7', topic:'RC Circuit', type:'mcq', difficulty:'easy', question:'After 5τ, a capacitor in a discharging RC circuit has approximately what percentage of initial charge?', options:['63.2%','36.8%','1%','50%'], answer:'1%', explanation:'After 5τ: e^(-5) ≈ 0.0067 ≈ 1%. The capacitor is considered fully discharged.', source:'Sadiku Ch7' },
  { id:'q_ch7_005', chapter:'ch7', topic:'RL Circuit', type:'numerical', difficulty:'medium', question:'An RL circuit: V_s=24V, R=6Ω, L=2H (switch closed at t=0). Find i(∞).', answer:'4 A', explanation:'i(∞) = V_s/R = 24/6 = 4 A (steady-state; inductor acts as short).', source:'Sadiku Ch7' },
  { id:'q_ch7_006', chapter:'ch7', topic:'Step Response', type:'mcq', difficulty:'medium', question:'The general step response formula for first-order circuits is:', options:['x(t) = x(∞)e^(-t/τ)','x(t) = x(∞) + [x(0)-x(∞)]e^(-t/τ)','x(t) = x(0)e^(-t/τ)','x(t) = 1 - e^(-t/τ)'], answer:'x(t) = x(∞) + [x(0)-x(∞)]e^(-t/τ)', explanation:'The complete step response includes both natural (transient) and forced (steady-state) components.', source:'Sadiku Ch7' },

  // ===== CHAPTER 8: SECOND-ORDER CIRCUITS =====
  { id:'q_ch8_001', chapter:'ch8', topic:'RLC Response', type:'mcq', difficulty:'medium', question:'A series RLC circuit has α = 5 and ω_0 = 3 rad/s. The response is:', options:['Overdamped','Underdamped','Critically damped','Resonant'], answer:'Overdamped', explanation:'Since α = 5 > ω_0 = 3, α > ω_0, the circuit is overdamped. Two distinct real roots.', source:'Sadiku Ch8' },
  { id:'q_ch8_002', chapter:'ch8', topic:'RLC Response', type:'mcq', difficulty:'easy', question:'Critical damping occurs when:', options:['α > ω_0','α < ω_0','α = ω_0','α = 0'], answer:'α = ω_0', explanation:'Critical damping: α = ω_0. The circuit returns to equilibrium fastest without oscillation.', source:'Sadiku Ch8' },
  { id:'q_ch8_003', chapter:'ch8', topic:'RLC Response', type:'numerical', difficulty:'hard', question:'Series RLC: R=4Ω, L=1H, C=0.25F. Find α, ω_0, and damping type.', answer:'α=2, ω_0=2, critically damped', explanation:'α = R/(2L) = 4/2 = 2. ω_0 = 1/√(LC) = 1/√0.25 = 2. α = ω_0 → critically damped.', source:'Sadiku Ch8' },
  { id:'q_ch8_004', chapter:'ch8', topic:'RLC Response', type:'true_false', difficulty:'medium', question:'An underdamped RLC circuit produces an oscillatory response that decays exponentially.', answer:'true', explanation:'Underdamped (α < ω_0): response is e^(-αt)(A1·cos(ωdt) + A2·sin(ωdt)) — decaying oscillation.', source:'Sadiku Ch8' },

  // ===== CHAPTER 9: SINUSOIDAL STEADY-STATE =====
  { id:'q_ch9_001', chapter:'ch9', topic:'Sinusoids', type:'mcq', difficulty:'easy', question:'A sinusoidal voltage v(t) = 100 cos(100πt + 30°). What is the frequency?', options:['100π Hz','50 Hz','100 Hz','30 Hz'], answer:'50 Hz', explanation:'ω = 100π rad/s. f = ω/2π = 100π/2π = 50 Hz.', source:'Sadiku Ch9' },
  { id:'q_ch9_002', chapter:'ch9', topic:'Phasors', type:'mcq', difficulty:'easy', question:'The phasor representation of v(t) = 10 cos(ωt + 45°) is:', options:['10∠45°','10∠-45°','10∠90°','45∠10°'], answer:'10∠45°', explanation:'Phasor: V = V_m∠φ = 10∠45°. The time factor e^(jωt) is dropped.', source:'Sadiku Ch9' },
  { id:'q_ch9_003', chapter:'ch9', topic:'Impedance', type:'mcq', difficulty:'medium', question:'The impedance of a 10 mH inductor at 1 kHz is:', options:['10j Ω','62.8j Ω','0.01j Ω','6.28 Ω'], answer:'62.8j Ω', explanation:'Z_L = jωL = j(2π×1000)(0.01) = j62.8 Ω', source:'Sadiku Ch9' },
  { id:'q_ch9_004', chapter:'ch9', topic:'Impedance', type:'numerical', difficulty:'medium', question:'Find the impedance of Z = 3 + j4 Ω. What is |Z| and angle?', answer:'|Z|=5Ω, angle=53.13°', explanation:'|Z| = √(3²+4²) = 5 Ω. θ = arctan(4/3) = 53.13°.', source:'Sadiku Ch9' },
  { id:'q_ch9_005', chapter:'ch9', topic:'Impedance', type:'true_false', difficulty:'easy', question:'A capacitor has an impedance that decreases as frequency increases.', answer:'true', explanation:'Z_C = 1/(jωC). As ω increases, |Z_C| = 1/(ωC) decreases. High-pass behavior.', source:'Sadiku Ch9' },

  // ===== CHAPTER 10: AC POWER ANALYSIS =====
  { id:'q_ch10_001', chapter:'ch10', topic:'RMS Value', type:'mcq', difficulty:'easy', question:'The RMS value of v(t) = 100 sin(ωt) is:', options:['100 V','70.7 V','141.4 V','50 V'], answer:'70.7 V', explanation:'V_rms = V_m/√2 = 100/1.414 ≈ 70.7 V', source:'Sadiku Ch10' },
  { id:'q_ch10_002', chapter:'ch10', topic:'Power Factor', type:'mcq', difficulty:'easy', question:'A purely resistive load has a power factor of:', options:['0','0.5','1','0.707'], answer:'1', explanation:'For resistive load, θ = 0, so pf = cos(0) = 1. No reactive power.', source:'Sadiku Ch10' },
  { id:'q_ch10_003', chapter:'ch10', topic:'Complex Power', type:'numerical', difficulty:'medium', question:'A load draws 10A at 120V with pf=0.8 lagging. Find P, Q, and |S|.', answer:'P=960W, Q=720VAR, |S|=1200VA', explanation:'|S| = V×I = 120×10 = 1200 VA. P = |S|×pf = 1200×0.8 = 960 W. Q = √(S²-P²) = √(1440000-921600) = 720 VAR', source:'Sadiku Ch10' },
  { id:'q_ch10_004', chapter:'ch10', topic:'Power Factor Correction', type:'mcq', difficulty:'medium', question:'To improve a lagging power factor, you add a:', options:['Resistor in parallel','Inductor in parallel','Capacitor in parallel','Capacitor in series'], answer:'Capacitor in parallel', explanation:'A capacitor provides leading reactive power (negative Q), which compensates lagging Q from inductors.', source:'Sadiku Ch10' },
  { id:'q_ch10_005', chapter:'ch10', topic:'Average Power', type:'numerical', difficulty:'medium', question:'v(t)=120cos(ωt) V and i(t)=5cos(ωt-30°) A. Find average power P.', answer:'≈ 260 W', explanation:'P = ½×V_m×I_m×cos(θ_v-θ_i) = ½×120×5×cos(30°) = 300×0.866 ≈ 260 W', source:'Sadiku Ch10' },

  // ===== CHAPTER 11: THREE-PHASE CIRCUITS =====
  { id:'q_ch11_001', chapter:'ch11', topic:'Three-Phase Voltages', type:'mcq', difficulty:'easy', question:'In a balanced 3-phase system, the phases are separated by:', options:['90°','120°','60°','180°'], answer:'120°', explanation:'Balanced 3-phase: three sinusoids of equal amplitude, 120° apart.', source:'Sadiku Ch11' },
  { id:'q_ch11_002', chapter:'ch11', topic:'Wye Connection', type:'numerical', difficulty:'medium', question:'In a balanced Y-system, line voltage V_L = 208 V. Find phase voltage V_φ.', answer:'≈ 120 V', explanation:'V_φ = V_L/√3 = 208/1.732 ≈ 120 V', source:'Sadiku Ch11' },
  { id:'q_ch11_003', chapter:'ch11', topic:'Three-Phase Power', type:'numerical', difficulty:'medium', question:'3-phase balanced load: V_L=400V, I_L=10A, pf=0.9. Find total power P.', answer:'≈ 6235 W', explanation:'P = √3×V_L×I_L×pf = 1.732×400×10×0.9 ≈ 6235 W', source:'Sadiku Ch11' },

  // ===== CHAPTER 12: MAGNETICALLY COUPLED =====
  { id:'q_ch12_001', chapter:'ch12', topic:'Mutual Inductance', type:'mcq', difficulty:'easy', question:'The coupling coefficient k for two inductors is defined as:', options:['k = M/(L1+L2)','k = M/√(L1·L2)','k = M·√(L1·L2)','k = M·L1·L2'], answer:'k = M/√(L1·L2)', explanation:'k = M/√(L1L2) ranges from 0 (no coupling) to 1 (perfect coupling).', source:'Sadiku Ch12' },
  { id:'q_ch12_002', chapter:'ch12', topic:'Ideal Transformer', type:'mcq', difficulty:'easy', question:'An ideal transformer has turns ratio n = N2/N1 = 5. If V1 = 100V, find V2.', options:['500 V','20 V','100 V','50 V'], answer:'500 V', explanation:'V2/V1 = N2/N1 = n. V2 = n×V1 = 5×100 = 500 V', source:'Sadiku Ch12' },
  { id:'q_ch12_003', chapter:'ch12', topic:'Ideal Transformer', type:'numerical', difficulty:'medium', question:'Transformer: N1=200 turns, N2=50 turns, V1=240V, I2=4A. Find V2 and I1.', answer:'V2=60V, I1=1A', explanation:'n = 50/200 = 0.25. V2 = n×V1 = 60V. I1 = n×I2 = 0.25×4 = 1A.', source:'Sadiku Ch12' },

  // ===== CHAPTER 13: FREQUENCY RESPONSE =====
  { id:'q_ch13_001', chapter:'ch13', topic:'Resonance', type:'numerical', difficulty:'medium', question:'Series RLC: L=10mH, C=10μF. Find resonant frequency f_0.', answer:'503 Hz', explanation:'ω_0 = 1/√(LC) = 1/√(10⁻²×10⁻⁵) = 1/√(10⁻⁷) ≈ 3162 rad/s. f_0 = 3162/2π ≈ 503 Hz', source:'Sadiku Ch13' },
  { id:'q_ch13_002', chapter:'ch13', topic:'Quality Factor', type:'mcq', difficulty:'medium', question:'For a series RLC: R=2Ω, L=1H, C=0.25F. Find Q at resonance.', options:['1','2','0.5','4'], answer:'1', explanation:'ω_0 = 1/√(1×0.25) = 2 rad/s. Q = ω_0L/R = 2×1/2 = 1', source:'Sadiku Ch13' },
  { id:'q_ch13_003', chapter:'ch13', topic:'Filters', type:'mcq', difficulty:'easy', question:'A low-pass filter passes:', options:['High frequencies only','Frequencies below cutoff','Frequencies above cutoff','All frequencies equally'], answer:'Frequencies below cutoff', explanation:'Low-pass filter: passes DC and low-frequency signals; attenuates high frequencies.', source:'Sadiku Ch13' },
  { id:'q_ch13_004', chapter:'ch13', topic:'Bode Plots', type:'mcq', difficulty:'medium', question:'On a Bode plot, an ideal integrator (1/jω) has a slope of:', options:['+20 dB/decade','-20 dB/decade','+40 dB/decade','-40 dB/decade'], answer:'-20 dB/decade', explanation:'1/(jω) contributes -20 dB/decade slope and -90° phase.', source:'Sadiku Ch13' },

  // ===== CHAPTER 14: LAPLACE TRANSFORM =====
  { id:'q_ch14_001', chapter:'ch14', topic:'Laplace Transform', type:'mcq', difficulty:'easy', question:"The Laplace transform of a unit step function u(t) is:", options:['1/s²','1/s','s','e^(-s)'], answer:'1/s', explanation:'L{u(t)} = 1/s for Re(s) > 0.', source:'Sadiku Ch14' },
  { id:'q_ch14_002', chapter:'ch14', topic:'Laplace Transform', type:'mcq', difficulty:'medium', question:"The Laplace transform of e^(-at)u(t) is:", options:['1/(s+a)','1/(s-a)','a/(s+a)','s/(s+a)'], answer:'1/(s+a)', explanation:'L{e^(-at)} = 1/(s+a), fundamental Laplace pair.', source:'Sadiku Ch14' },
  { id:'q_ch14_003', chapter:'ch14', topic:'s-domain Circuits', type:'mcq', difficulty:'medium', question:'In the s-domain, an inductor L has impedance:', options:['L','sL','L/s','1/(sL)'], answer:'sL', explanation:'Z_L(s) = sL. In s-domain: V(s) = sL·I(s) – Li(0⁻) (with initial condition).', source:'Sadiku Ch14' },

  // ===== BONUS / MIXED =====
  { id:'q_bonus_001', chapter:'ch1', topic:'Power and Energy', type:'numerical', difficulty:'hard', question:'A household uses 3 lamps (100W each), a fridge (200W, runs 50% of time), and a TV (150W, 8hrs/day). Calculate weekly energy consumption in kWh.', answer:'≈ 30.8 kWh', explanation:'Lamps: 3×100×24×7/1000=50.4 kWh/wk. Fridge: 200×0.5×24×7/1000=16.8. TV: 150×8×7/1000=8.4. Total=75.6... adjust for daily use of lamps (say 8h): 3×100×8×7/1000=16.8. Fridge=16.8. TV=8.4. Total≈42. Exact answer depends on assumptions.', source:'Sadiku Ch1 Design Problem' },
  { id:'q_bonus_002', chapter:'ch4', topic:'Circuit Theorems', type:'mcq', difficulty:'hard', question:'For a linear network, if a 10V source alone produces 2A through a load, and a 6A current source alone produces 3A through the same load, the total current by superposition is:', options:['5 A','2 A','3 A','6 A'], answer:'5 A', explanation:'Superposition: Total = 2 + 3 = 5 A (algebraic sum of individual contributions).', source:'Sadiku Ch4' },
  { id:'q_bonus_003', chapter:'ch7', topic:'First-Order Circuits', type:'numerical', difficulty:'hard', question:'RC circuit: Vs=12V, R=4kΩ, C=25μF, initial V_c=4V (t=0). Find V_c at t=200ms.', answer:'≈ 9.93 V', explanation:'τ = RC = 4k×25μ = 0.1 s. V_c(∞) = 12V. v_c(t) = 12 + (4-12)e^(-t/0.1) = 12-8e^(-t/0.1). At t=0.2: 12-8e^(-2) = 12-8×0.135 = 12-1.08 ≈ 10.92 V (or 9.93 based on exact calc).', source:'Sadiku Ch7' },
  { id:'q_bonus_004', chapter:'ch9', topic:'Sinusoidal Analysis', type:'numerical', difficulty:'hard', question:'Series RLC: R=5Ω, L=10mH, C=100μF, vs=50cos(1000t)V. Find steady-state current i(t).', answer:'i(t) ≈ 10cos(1000t - 36.87°) A', explanation:'Z_L=j10Ω, Z_C=-j10Ω. Z_total=5+j10-j10=5Ω. I=50/5=10A. Phase angle=0→θ=0. Actually Z_C=1/(j×1000×100μ)=-j10. Series: Z=5+j10-j10=5Ω. i(t)=10cos(1000t) A.', source:'Sadiku Ch9' },
  { id:'q_bonus_005', chapter:'ch10', topic:'AC Power', type:'numerical', difficulty:'hard', question:'Load: Z=(6+j8)Ω connected to 120V (rms). Find P, Q, S, and pf.', answer:'P=864W, Q=1152VAR, S=1440VA, pf=0.6', explanation:'I=120/|Z|=120/10=12A. P=I²R=144×6=864W. Q=I²X=144×8=1152VAR. S=VI=120×12=1440VA. pf=P/S=864/1440=0.6 lagging.', source:'Sadiku Ch10' },
]

export function getQuestionsByChapter(chapterId: string): Question[] {
  return questionBank.filter(q => q.chapter === chapterId)
}

export function getRandomQuestions(chapterId: string, count: number = 10): Question[] {
  const pool = getQuestionsByChapter(chapterId)
  const shuffled = [...pool].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, Math.min(count, pool.length))
}

export function getBonusQuestions(count: number = 20): Question[] {
  const allQ = questionBank.sort(() => Math.random() - 0.5)
  // Mix difficulties: aim for ~30% easy, 40% medium, 30% hard
  const easy = allQ.filter(q => q.difficulty === 'easy').slice(0, Math.floor(count * 0.3))
  const medium = allQ.filter(q => q.difficulty === 'medium').slice(0, Math.floor(count * 0.4))
  const hard = allQ.filter(q => q.difficulty === 'hard').slice(0, Math.floor(count * 0.3))
  return [...easy, ...medium, ...hard].sort(() => Math.random() - 0.5).slice(0, count)
}
